### ISSUE TITLE
Hyperdrive - Hypermedia API client in Swift

### ISSUE THREAD

**Issue by kylef** [OpenSourceShowAndTell/SanFrancisco_April2015#10]
Hyperdrive is a Hypermedia and API Blueprint client in Swift, supporting HAL, Siren and any API described by an API Blueprint. It's not OSS as of creating this issue, but it will be released this week. Internally it makes use of the [Representor](https://github.com/the-hypermedia-project/representor-swift#representor-in-swift) pattern.

**Comment by elof** [comment]
+1 look forward to hearing more.

**Comment by kylef** [comment]
Closing the issue since this has been done. Thanks @elof.
