### ISSUE TITLE
Calling DevOps: teaming with network admins made easy with Opensource Distributed Networking

### ISSUE THREAD

**Issue by susanwu88** [OpenSourceShowAndTell/SanFrancisco_April2015#12]
Calling DevOps, raise your hand if you get along swimmingly with the network admins.  Really? Check out MidoNet, which is the open source project for network virtualization overlay (NVO).  MidoNet is a software abstraction between the end hosts and the physical network and virtualizes the network.

**Comment by elof** [comment]
Hi Susan. Thanks for submitting this topic. While this sounds interesting the event is designed for open source contributors or project owners, so we won't be able to accept your talk. We'd love to meet you and have you come out to learn with us though. Hope to see you on Friday.

**Comment by susanwu88** [comment]
Midokura is the company behind the opensource MidoNet project (midonet.org). I personally don't contribute but many engineers at Midokura as well as community members contribute to the project.
