### ISSUE TITLE
Lightning talk: Apache Mesos and its ecosystem

### ISSUE THREAD

**Issue by davelester** [OpenSourceShowAndTell/SanFrancisco_April2015#17]
I would like to give a talk about [Apache Mesos](http://mesos.apache.org), a cluster manager which abstracts machines away from applications, making it possible to orchestrate containers across a shared pool of servers. I'd give particular focus to the [ecosystem of frameworks](http://mesos.apache.org/documentation/latest/mesos-frameworks/) for the project for running services, batch, and soon storage on the same cluster.

**Comment by elof** [comment]
+1 Look forward to this! We use Mesos at Keen :+1: 

Talk format is 10min including Q&A. We'll have a projector and a white board if you need either, but they aren't required.

**Comment by lambtron** [comment]
:hamburger:

**Comment by elof** [comment]
We're doing another OSSAT later this month and would love to have you back out. Check it out http://opensourceshowandtell.com/

**Comment by elof** [comment]
Hey Dave. Hope you're doing well! We're putting on the next OSSAT in a couple weeks and would love to have you join us. Let me know if you have any questions at all.

http://opensourceshowandtell.com

Would be great to have a little help getting the word out if you're up to that too?

**Comment by davelester** [comment]
@elof thanks for the ping! I'll close this issue for now since I'm no longer quite as plugged into the Mesos ecosystem, but I'm happy to help spread the word and see I can find another speaker to present about the project.
